[tool.poetry]
name = "chapter-01-1"
version = "0.1.0"
description = ""
authors = ["jee1021 <dlawldnjs460@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.13"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
