[tool.poetry]
name = "chapter02"
version = "0.1.0"
description = ""
authors = ["jee1021 <dlawldnjs460@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "3.12"
django = "^5.2.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
